### ISSUE TITLE
No trailing newline in help message

### ISSUE THREAD

**Issue by HiFaraz** [mitranim/gow#13]
Hi, your trailing newline in your help message is trimmed away by your call to `strings.TrimSpace`:

https://github.com/mitranim/gow/blob/d60314a242a5b63ba662051a507f5d2c8ae95c42/gow.go#L28

Discovered it through playing with `gow` in my terminal.

Thanks for this useful package1

**Comment by mitranim** [comment]
Fixed. Somehow my terminal was adding a newline so I didn't notice. Was it mixing with the next prompt in yours?

**Comment by mitranim** [comment]
Should be fine now, thanks for reporting.

**Comment by HiFaraz** [comment]
Thank you!
