### ISSUE TITLE
Add flag fro adding more folders

### ISSUE THREAD

**Issue by justgook** [mitranim/gow#21]
I have mono repo where I’m developing multiple go applications, and same repo also contains “common module” that is used by multiple packages at once.. 

go.mod contains:
`replace myApp/common => ../common`

It would be nice to trigger `gow` to reload, when I changing something in that `common` folder..

maybe something like `gow run -w=../common,../other-common .`

**Comment by mitranim** [comment]
Done: https://github.com/mitranim/gow/commit/2499c47489c1dc7f774bdf2e89c01650bbbf61c2.

Also made an unrelated breaking change where it clears the terminal only on restart, not on launch. This makes it more compatible with build systems that run multiple watchers simultaneously.

**Comment by justgook** [comment]
just saved me a few hours a day - trying to figure out why my changes do not work...
