### ISSUE TITLE
Issue installing it on MacOS: Slice does not match []Elem

### ISSUE THREAD

**Issue by firminochangani** [mitranim/gow#25]
Hi, I am having the issues displayed on the screenshot below while attempting to install on a MacOS 12.4 (ARM)

![Screenshot 2022-06-18 at 18 14 49](https://user-images.githubusercontent.com/1679333/174449455-a9713772-9d98-44eb-83a4-805f5ee0fefd.png)

**Comment by mitranim** [comment]
Which Go version? My system still has 1.18, and I haven't tested newer ones, expecting backwards compatibility in minor releases.

**Comment by firminochangani** [comment]
Currently I am using the following version: `go1.18beta2 darwin/arm64`

**Comment by mitranim** [comment]
Updated to Go 1.18.3, still unable to reproduce. I'm on MacOS Intel. Please consider updating Go and rechecking.

**Comment by mitranim** [comment]
Let me know if this recurs with modern versions.
