### ISSUE TITLE
trapping returns?

### ISSUE THREAD

**Issue by kswope** [mitranim/gow#27]
I prefer gow over everything else I've tried but what makes me nuts is that it doesn't allow any input.   Who hasn't occasionally held the return key to put some blank space in the tailed output to clear the screen or just make new output more obvious?  I've never seen this before, what is causing it, and can it be taken out?

**Comment by mitranim** [comment]
It's because when running in raw terminal mode (default), `gow` doesn't echo stdin back to stdout. You can disable raw mode with `-r=false`. Raw mode is required for `gow`'s hotkeys, so disabling raw mode also disables hotkeys. It should also be possible to hack `gow` to add an echo option. I'm unable to make promises. Let me know if you want to make a PR, I could advise.

**Comment by mitranim** [comment]
I should note that many terminals have a hotkey for clearing the buffer. In default MacOS Terminal, the hotkey is ⌘K. I prefer this over hitting Enter multiple times.

**Comment by kswope** [comment]
I didn't realize that everything, including tail, etc were deliberately doing that, I assumed it was some terminal thing that just happened automatically since its the behavior of *everything* I've used in the past 30 years.  I guess its no big deal, but I'll admit if you don't know whats going on it almost feels broken.

**Comment by mitranim** [comment]
To clarify: by default, terminals operate in "cooked mode" which automatically echoes stdin to stdout without any involvement of the running program. `gow` by default switches the terminal into "raw mode" to support hotkeys, explicitly disabling echoing: https://github.com/mitranim/gow/blob/9c7b31992631b27b1a0f31b819a0345deadc60f8/gow_term.go#L42

If this behavior is strange to users, I might look into enabling it.

**Comment by mitranim** [comment]
Fixed in 11705ebc30f58ef0ec126d9bb7589d2711028d1f.

**Comment by kswope** [comment]
Works nicely but I noticed a strange side effect, no big deal,  but you have to ctrl-c twice to exit.  By adding expected behavior we ended up with different unexpected behavior :)

    [gow] received ^C^C, shutting down

**Comment by mitranim** [comment]
Entirely intentional. By default, signal codes from stdin are sent to the subprocess (if any). To affect `gow` itself, you need to hit the hotkey twice within 1s:

```
[gow] received ^C, stopping subprocess
[gow] received ^C^C, shutting down
```

(Also it always worked like this, and is unrelated to the recent changes.)

**Comment by kswope** [comment]
Oh I see, it was there before.  Never needed anything like that myself.  But I suppose it would be useful for a runaway process.

What would be really useful is a way to restart,  like nodemon has 'rs'

**Comment by mitranim** [comment]
`gow` has a better way: hotkeys. Check the readme. 🙂
