### ISSUE TITLE
Go.mod watch in addition to go files

### ISSUE THREAD

**Issue by hunterdishner** [mitranim/gow#3]
I noticed you had a tool for general file watching but it would be nice if gow also watched the go.mod file for changes. Sometimes we forget to update a reference to a package and then push a change that just updates the go.mod.

**Comment by mitranim** [comment]
Apologies for the late response.

This is similar to issue #2, but I could see supporting `go.mod` and possibly `go.sum` by default, since they're strictly Go-related. I'll kick it around locally to see if any issues come up.

**Comment by mitranim** [comment]
Enabled watching `*.mod` files, used for a few weeks, haven't noticed any issues. Just pushed an update to enable this for everyone. If this ends up problematic for some users, we might revert this. Anyway try it out, let me know how it works. 🙂

**Comment by hunterdishner** [comment]
Sweet, I'll try to work it into our next sprint and testing cycle. I'll let you know if I run into any issues.
