### ISSUE TITLE
Clear does not work?

### ISSUE THREAD

**Issue by danawoodman** [mitranim/gow#38]
On macOS, running `gow -c run main.go` on a hello world go file does not clear the terminal on iTerm or VSCode.

Is this behavior known to be broken?

Go v 1.21

**Comment by mitranim** [comment]
The handling of escape sequences related to clearing is known to be inconsistent between terminals. I use MacOS. Clearing seems to work in the built-in terminal and in iTerm 3.4.8. Not sure about VSCode, might set up to check later. I made changes in `gow` related to terminal clearing a few months ago. If your `gow` version is older, try updating. Also please specify your iTerm version.

**Comment by danawoodman** [comment]
Strange, it is now clearing, not sure what happened but I updated to latest just in case. Sorry for the false report!
