### ISSUE TITLE
Add a LICENSE.md so the pkg.go.dev language page works

### ISSUE THREAD

**Issue by deltamualpha** [mitranim/gow#4]
https://pkg.go.dev/mod/github.com/mitranim/gow@v0.0.0-20200224120608-b81929fa78db

It'd be nice to have the README rendering on that landing page, right? Although https://pkg.go.dev/license-policy doesn't list the WTFPL as an acceptable license...

**Comment by mitranim** [comment]
Thanks for letting me know. I've been sticking with `godoc.org` and wasn't aware.

I'd appreciate suggestions for a solution that doesn't involve sticking legal BS texts into a code repository. Developers shouldn't be forced to deal with this crap. Feeding the trolls seems like a bad policy.

**Comment by mitranim** [comment]
Should be resolved by #7.
