### ISSUE TITLE
Support debugging

### ISSUE THREAD

**Issue by chriskolenko** [mitranim/gow#43]
While using `gow` I would like to be able to attach a debugger. 

Apparently building with; `-gcflags=all="-N -l"` will allow debugging.

https://github.com/golang/vscode-go/blob/master/docs/debugging.md#attach

**Comment by mitranim** [comment]
While that's useful to know, it's not immediately clear to me why `gow` would need to "support" this. `gow` simply passes a slice of arguments to the `go` executable (which can be replaced with `-g`), as-is.

**Comment by mitranim** [comment]
To clarify, I assume you want to attach a debugger to your app's process, which is a subprocess spawned by `gow`. To make that possible, you'd need to pass these flags to `gow` after the name of the `go` subcommand, like this:

```sh
gow -c -v run <various_go_flags> -gcflags=all="-N -l" <app_path>
```

**Comment by chriskolenko** [comment]
In the end I wasn't able to get the run command to work with debugging. `-gcflags=all="-N -l"` seems to work differently when running via interpreter than compiler.

**Comment by akosyakov** [comment]
@mitranim I tried to use what you proposed but it does not work. These flags has to be passed to go build as it seems not to go run.

**Comment by mitranim** [comment]
Thanks for the clarification. My suggestion was a shot in the dark because I haven't used debuggers with Go.
