### ISSUE TITLE
feature request: clear screen

### ISSUE THREAD

**Issue by wzsayhi** [mitranim/gow#45]
Maybe it would be good to use with clear screen shourtcut (ctrl+l) like bash?

**Comment by mitranim** [comment]
Terminals tend to have a built-in hotkey for screen clearing. For example, the MacOS Terminal uses ⌘K, which seems to work regardless of the current foreground app (including `gow`). I would suggest checking your terminal's settings.

**Comment by wzsayhi** [comment]
Thanks for your reply, I found the answer for the terminal I'm using (microsoft/terminal#10906).
