### ISSUE TITLE
Only rerun changed test files

### ISSUE THREAD

**Issue by Altiano** [mitranim/gow#5]
Is this only re-run tests that depend on the changed files?

**Comment by mitranim** [comment]
`gow` reruns its command on any change to the `*.go` or `go.mod` files in the current directory. When testing, you use `gow test`, which effectivelly runs `go test` on any change. `go test` already tries to cache and reuse test results, so `gow` doesn't need to implement this.

**Comment by mitranim** [comment]
I'm gonna close this, since it doesn't appear to be an actual issue or deliverable feature in scope for `gow`. Let me know if you have suggestions to the contrary.
